### ISSUE TITLE
when I insert the fileheader for a python file, it prompts up below error

### ISSUE THREAD

**Issue by elfprincexu** [caizhengxin/vscodefileheader#22]
2023-10-10 02:19:10.218 [error] TypeError: s is not iterable
	at Template.isIgnore (/home/******/.vscode/extensions/jankincai.vscodefileheader-0.9.1/out/editor.js:40:25)
	at Template.update (/home/******/.vscode/extensions/jankincai.vscodefileheader-0.9.1/out/template.js:227:19)
	at Object.updateTemplateCommand (/home/******/.vscode/extensions/jankincai.vscodefileheader-0.9.1/out/command.js:74:17)
	at /home/******/.vscode/extensions/jankincai.vscodefileheader-0.9.1/out/extension.js:91:17
	at r.h (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:82744)
	at r.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:83604)
	at i.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10813)
	at i.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10579)
	at i.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:9660)
	at i.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:8736)
	at n.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:7566)
	at m.w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at w.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
	at n.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:7901)
	at m.w (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at w.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:135:6181)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) extension.fileheader {"value":"jankincai.vscodefileheader","_lower":"jankincai.vscodefileheader"}

**Comment by elfprincexu** [comment]
settings for the fileheader 

    "fileheader.author": "my name",
    "fileheader.body": false,
    "fileheader.open": false,
    "fileheader.save": false,
    "fileheader.header_max_line": 10,
    "fileheader.dateformat": "YYYY-MM-DD HH:mm:ss",
    "fileheader.file_suffix_mapping": {
        ".py": "Python",
    },
    "fileheader.ignore": [
        "*.txt",           
    ],
    "fileheader.remote": "https://github.com/caizhengxin/vscodefileheader.git"

**Comment by caizhengxin** [comment]
Hi, del "fileheader.remote", the error path.

**Comment by caizhengxin** [comment]
> settings for the fileheader
> 
> ```
> "fileheader.author": "my name",
> "fileheader.body": false,
> "fileheader.open": false,
> "fileheader.save": false,
> "fileheader.header_max_line": 10,
> "fileheader.dateformat": "YYYY-MM-DD HH:mm:ss",
> "fileheader.file_suffix_mapping": {
>     ".py": "Python",
> },
> "fileheader.ignore": [
>     "*.txt",           
> ],
> "fileheader.remote": "https://github.com/caizhengxin/vscodefileheader.git"
> ```

Hi, del "fileheader.remote", the error path.
